/*
 * This GUI class is used to create/edit/inspect a single battle.
 * The class is used when opening up a battle through the tournament GUI.
 */
package GUI.TournamentRelated;

import BE.StopWatch;
import BE.Tournaments.Abstract_Tournament;
import BE.Tournaments.Battles.Battle;
import BLL.Facades.FacadeToBLL;
import BLL.TournamentTypes.SuperTournament;
import GUI.FighterLookerGUI;
import GUI.TableModels_And_Tables.BattleWarningsTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Simon, Martin, Alex, Casper
 */
public class SingleBattleDetailsGUI extends javax.swing.JDialog {

    /**
     * Variables
     */
    private Battle battle;
    private java.awt.Frame frame;
    private Timer timer;
    private StopWatch stopWatch;
    private Abstract_Tournament at;
    private FacadeToBLL facadeToBLL = FacadeToBLL.getInstance();
    private BattleWarningsTableModel redWarnings;
    private BattleWarningsTableModel blueWarnings;

    /**
     * Creates new form NewJFrame
     *
     * @param parent
     * @param modal
     * @param battle
     */
    public SingleBattleDetailsGUI(java.awt.Frame parent, boolean modal, Battle battle, Abstract_Tournament at) {
        super(parent, modal);
        this.frame = parent;
        this.battle = battle;
        this.at = at;
        initComponents();
        timer = new Timer(50, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                stopWatch.start(50);
                lblTimer.setText(stopWatch.toString());

            }
        });

        setFieldsToReceivedInfo();
        setVisible(true);
    }

    private void setFieldsToReceivedInfo() {
        //Set the warning lists
        redWarnings = new BattleWarningsTableModel(battle.getRedWarnings());
        blueWarnings = new BattleWarningsTableModel(battle.getBlueWarnings());
        tblRedWarnings.setModel(redWarnings);
        tblBlueWarnings.setModel(blueWarnings);
        //Sets the red buttons
        btnRedGivePoint.setEnabled(battle.getFighter1Red() != null);
        btnRedTakePoint.setEnabled(battle.getFighter1Red() != null);
        btnRedGiveWarning.setEnabled(battle.getFighter1Red() != null);
        btnRedRemoveWarning.setEnabled(battle.getFighter1Red() != null);
        btnCheckRed.setEnabled(battle.getFighter1Red() != null);
        //Sets the blue buttons
        btnBlueGivePoint.setEnabled(battle.getFighter2Blue() != null);
        btnBlueTakePoint.setEnabled(battle.getFighter2Blue() != null);
        btnBlueGiveWarning.setEnabled(battle.getFighter2Blue() != null);
        btnBlueRemoveWarning.setEnabled(battle.getFighter2Blue() != null);
        btnCheckBlue.setEnabled(battle.getFighter2Blue() != null);

        if (battle.getFighter1Red() != null) {
            lblRedPoints.setText("" + battle.getRedPoint());
            lblRedName.setText(battle.getFighter1Red().getName());
        }
        if (battle.getFighter2Blue() != null) {
            lblBluePoints.setText("" + battle.getBluePoint());
            lblBlueName.setText(battle.getFighter2Blue().getName());
        }

        stopWatch = battle.getStopWatch();
        lstStopWatch.setListData(stopWatch.getTimeList().toArray());

        lblTimer.setText(stopWatch.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rbgrFighter = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        pnlRed = new javax.swing.JPanel();
        btnCheckRed = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnRedGivePoint = new javax.swing.JButton();
        btnRedTakePoint = new javax.swing.JButton();
        lblRedPoints = new javax.swing.JLabel();
        btnRedGivePoint1 = new javax.swing.JButton();
        btnRedGivePoint2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnRedGiveWarning = new javax.swing.JButton();
        btnRedRemoveWarning = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jspTournaments = new javax.swing.JScrollPane();
        tblRedWarnings = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblRedName = new javax.swing.JLabel();
        pnlBlue = new javax.swing.JPanel();
        btnCheckBlue = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBlueGivePoint = new javax.swing.JButton();
        lblBluePoints = new javax.swing.JLabel();
        btnBlueTakePoint = new javax.swing.JButton();
        btnBlueGivePoint1 = new javax.swing.JButton();
        btnBlueGivePoint2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnBlueGiveWarning = new javax.swing.JButton();
        btnBlueRemoveWarning = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jspTournaments1 = new javax.swing.JScrollPane();
        tblBlueWarnings = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblBlueName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTimer = new javax.swing.JLabel();
        btnTimerReset = new javax.swing.JButton();
        btnTimerNewLap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstStopWatch = new javax.swing.JList();
        btnRemoveNew = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kampdetaljer");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
        });

        btnCancel.setText("Annuller");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        btnSaveChanges.setText("Afslut Kamp");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaveChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveChanges)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSaveChanges))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Spiller"));

        pnlRed.setBorder(javax.swing.BorderFactory.createTitledBorder("Rød"));

        btnCheckRed.setText("Se/rediger kæmper info");
        btnCheckRed.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCheckRedActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Point"));

        btnRedGivePoint.setText("+++");
        btnRedGivePoint.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRedGivePointActionPerformed(evt);
            }
        });

        btnRedTakePoint.setText("-");
        btnRedTakePoint.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRedTakePointActionPerformed(evt);
            }
        });

        lblRedPoints.setText("0");

        btnRedGivePoint1.setText("++");
        btnRedGivePoint1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRedGivePoint1ActionPerformed(evt);
            }
        });

        btnRedGivePoint2.setText("+");
        btnRedGivePoint2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRedGivePoint2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btnRedGivePoint2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRedGivePoint1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblRedPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnRedGivePoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRedTakePoint, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblRedPoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRedGivePoint)
                    .addComponent(btnRedGivePoint2)
                    .addComponent(btnRedGivePoint1)
                    .addComponent(btnRedTakePoint)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Advarsler"));

        btnRedGiveWarning.setText("Giv Advarsel");
        btnRedGiveWarning.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRedGiveWarningActionPerformed(evt);
            }
        });

        btnRedRemoveWarning.setText("Fjern advarsel");
        btnRedRemoveWarning.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRedRemoveWarningActionPerformed(evt);
            }
        });

        jLabel4.setText("Liste over advarsler givet");

        jspTournaments.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblRedWarnings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Title 1"
            }
        ));
        jspTournaments.setViewportView(tblRedWarnings);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRedGiveWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(btnRedRemoveWarning)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jspTournaments, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRedGiveWarning)
                    .addComponent(btnRedRemoveWarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jspTournaments, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Kæmper:");

        lblRedName.setText("ingen kæmper");

        javax.swing.GroupLayout pnlRedLayout = new javax.swing.GroupLayout(pnlRed);
        pnlRed.setLayout(pnlRedLayout);
        pnlRedLayout.setHorizontalGroup(
            pnlRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheckRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlRedLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRedName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlRedLayout.setVerticalGroup(
            pnlRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRedLayout.createSequentialGroup()
                .addGroup(pnlRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblRedName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckRed)
                .addContainerGap())
        );

        pnlBlue.setBorder(javax.swing.BorderFactory.createTitledBorder("Blå"));

        btnCheckBlue.setText("Se/rediger kæmper info");
        btnCheckBlue.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCheckBlueActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Point"));

        btnBlueGivePoint.setText("+++");
        btnBlueGivePoint.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBlueGivePointActionPerformed(evt);
            }
        });

        lblBluePoints.setText("0");

        btnBlueTakePoint.setText("-");
        btnBlueTakePoint.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBlueTakePointActionPerformed(evt);
            }
        });

        btnBlueGivePoint1.setText("++");
        btnBlueGivePoint1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBlueGivePoint1ActionPerformed(evt);
            }
        });

        btnBlueGivePoint2.setText("+");
        btnBlueGivePoint2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBlueGivePoint2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBlueGivePoint2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnBlueGivePoint1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBluePoints, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBlueGivePoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBlueTakePoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblBluePoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBlueGivePoint2)
                    .addComponent(btnBlueGivePoint)
                    .addComponent(btnBlueGivePoint1)
                    .addComponent(btnBlueTakePoint)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Advarsler"));

        btnBlueGiveWarning.setText("Giv Advarsel");
        btnBlueGiveWarning.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBlueGiveWarningActionPerformed(evt);
            }
        });

        btnBlueRemoveWarning.setText("Fjern advarsel");
        btnBlueRemoveWarning.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBlueRemoveWarningActionPerformed(evt);
            }
        });

        jLabel5.setText("Liste over advarsler givet");

        jspTournaments1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblBlueWarnings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Title 1"
            }
        ));
        jspTournaments1.setViewportView(tblBlueWarnings);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnBlueGiveWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBlueRemoveWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jspTournaments1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBlueGiveWarning)
                    .addComponent(btnBlueRemoveWarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspTournaments1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setText("Kæmper:");

        lblBlueName.setText("ingen kæmper");

        javax.swing.GroupLayout pnlBlueLayout = new javax.swing.GroupLayout(pnlBlue);
        pnlBlue.setLayout(pnlBlueLayout);
        pnlBlueLayout.setHorizontalGroup(
            pnlBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBlueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBlueLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBlueName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBlueLayout.setVerticalGroup(
            pnlBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBlueLayout.createSequentialGroup()
                .addGroup(pnlBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBlueName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCheckBlue)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Timer"));

        lblTimer.setText("Timer");

        btnTimerReset.setText("Nulstil");
        btnTimerReset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnTimerResetActionPerformed(evt);
            }
        });

        btnTimerNewLap.setText("Ny runde");
        btnTimerNewLap.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnTimerNewLapActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstStopWatch);

        btnRemoveNew.setText("Fjern seneste runde");
        btnRemoveNew.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemoveNewActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Start/stop");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tid:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimerReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimerNewLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTimer)
                            .addComponent(jLabel7))
                        .addGap(10, 10, 10)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimerReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimerNewLap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveNew))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed

        findAndSetWinner();
        //Reset the points.

        if (battle.getFighter1Red() != null) {
            battle.setRedPoint(battle.getRedPoint());
            battle.getFighter1Red().setPoint(Integer.parseInt(lblRedPoints.getText()));
        }
        if (battle.getFighter2Blue() != null) {
            battle.setBluePoint(battle.getBluePoint());
            battle.getFighter2Blue().setPoint(Integer.parseInt(lblBluePoints.getText()));
        }

        dispose();
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private synchronized void findAndSetWinner() throws NumberFormatException {
        //If both players are in the game, take the one with most points and set them as winner
        if (battle.getFighter1Red() != null && battle.getFighter2Blue() != null) {
            if (battle.getRedPoint() > battle.getBluePoint()) {
                battle.setWinner(battle.getFighter1Red());
            } else if (battle.getRedPoint() < battle.getBluePoint()) {
                battle.setWinner(battle.getFighter2Blue());
            } else if (battle.getRedPoint() == battle.getBluePoint()) {
                battle.setWinner(null);
            }
        } //If one of the players don't exsist, set the other as winner
        else if (battle.getFighter1Red() == null) {
            battle.setWinner(battle.getFighter2Blue());
        } else if (battle.getFighter2Blue() == null) {
            battle.setWinner(battle.getFighter1Red());
        }

    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setFieldsToReceivedInfo(); //reset info
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRedGivePointActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRedGivePointActionPerformed
    {//GEN-HEADEREND:event_btnRedGivePointActionPerformed
        battle.setRedPoint(battle.getRedPoint() + 3);
        lblRedPoints.setText("" + battle.getRedPoint());
    }//GEN-LAST:event_btnRedGivePointActionPerformed

    private void btnRedTakePointActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRedTakePointActionPerformed
    {//GEN-HEADEREND:event_btnRedTakePointActionPerformed
        battle.setRedPoint(battle.getRedPoint() - 1);
        lblRedPoints.setText("" + battle.getRedPoint());
    }//GEN-LAST:event_btnRedTakePointActionPerformed

    private void btnRedGiveWarningActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRedGiveWarningActionPerformed
    {//GEN-HEADEREND:event_btnRedGiveWarningActionPerformed
        battle.getRedWarnings().add(JOptionPane.showInputDialog("Skriv advarselstype"));
        redWarnings.updateWarningList(battle.getRedWarnings());
    }//GEN-LAST:event_btnRedGiveWarningActionPerformed

    private void btnRedRemoveWarningActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRedRemoveWarningActionPerformed
    {//GEN-HEADEREND:event_btnRedRemoveWarningActionPerformed
        int index = tblRedWarnings.getSelectedRow();
        if (index != -1) {
            battle.getRedWarnings().remove(tblRedWarnings.convertRowIndexToModel(index));
        }
        redWarnings.updateWarningList(battle.getRedWarnings());
    }//GEN-LAST:event_btnRedRemoveWarningActionPerformed

    private void btnCheckRedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCheckRedActionPerformed
    {//GEN-HEADEREND:event_btnCheckRedActionPerformed
        SuperTournament parentTournament = facadeToBLL.getSuperTournament(at.getParentId());
        FighterLookerGUI fighterLooker = new FighterLookerGUI(frame, true, battle.getFighter1Red(), parentTournament, null);
        fighterLooker.setVisible(true);
        lblRedName.setText(battle.getFighter1Red().getName());
    }//GEN-LAST:event_btnCheckRedActionPerformed

    private void btnCheckBlueActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCheckBlueActionPerformed
    {//GEN-HEADEREND:event_btnCheckBlueActionPerformed
        SuperTournament parentTournament = facadeToBLL.getSuperTournament(at.getParentId());
        FighterLookerGUI fighterLooker = new FighterLookerGUI(frame, true, battle.getFighter2Blue(), parentTournament, null);
        fighterLooker.setVisible(true);

        lblBlueName.setText(battle.getFighter2Blue().getName());
    }//GEN-LAST:event_btnCheckBlueActionPerformed

    private void btnBlueGiveWarningActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBlueGiveWarningActionPerformed
    {//GEN-HEADEREND:event_btnBlueGiveWarningActionPerformed
        battle.getBlueWarnings().add(JOptionPane.showInputDialog("Skriv advarselstype"));
        blueWarnings.updateWarningList(battle.getBlueWarnings());
    }//GEN-LAST:event_btnBlueGiveWarningActionPerformed

    private void btnBlueRemoveWarningActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBlueRemoveWarningActionPerformed
    {//GEN-HEADEREND:event_btnBlueRemoveWarningActionPerformed
        int index = tblBlueWarnings.getSelectedRow();
        if (index != -1) {
            battle.getBlueWarnings().remove(tblBlueWarnings.convertRowIndexToModel(index));
        }
        blueWarnings.updateWarningList(battle.getBlueWarnings());
    }//GEN-LAST:event_btnBlueRemoveWarningActionPerformed

    private void btnBlueTakePointActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBlueTakePointActionPerformed
    {//GEN-HEADEREND:event_btnBlueTakePointActionPerformed
        battle.setBluePoint(battle.getBluePoint() - 1);
        lblBluePoints.setText("" + battle.getBluePoint());
    }//GEN-LAST:event_btnBlueTakePointActionPerformed

    private void btnBlueGivePointActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBlueGivePointActionPerformed
    {//GEN-HEADEREND:event_btnBlueGivePointActionPerformed
        battle.setBluePoint(battle.getBluePoint() + 3);
        lblBluePoints.setText("" + battle.getBluePoint());
    }//GEN-LAST:event_btnBlueGivePointActionPerformed

    private void btnTimerResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnTimerResetActionPerformed
    {//GEN-HEADEREND:event_btnTimerResetActionPerformed
        stopWatch.reset();
        lblTimer.setText(stopWatch.toString());
    }//GEN-LAST:event_btnTimerResetActionPerformed

    private void btnTimerNewLapActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnTimerNewLapActionPerformed
    {//GEN-HEADEREND:event_btnTimerNewLapActionPerformed
        stopWatch.addLap();
        lstStopWatch.setListData(stopWatch.getTimeList().toArray());
    }//GEN-LAST:event_btnTimerNewLapActionPerformed

    private void btnRemoveNewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveNewActionPerformed
    {//GEN-HEADEREND:event_btnRemoveNewActionPerformed
        stopWatch.removeLap();
        lstStopWatch.setListData(stopWatch.getTimeList().toArray());
    }//GEN-LAST:event_btnRemoveNewActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (!timer.isRunning()) {
            timer.start();
        } else if (timer.isRunning()) {
            timer.stop();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnRedGivePoint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedGivePoint1ActionPerformed
        battle.setRedPoint(battle.getRedPoint() + 2);
        lblRedPoints.setText("" + battle.getRedPoint());
    }//GEN-LAST:event_btnRedGivePoint1ActionPerformed

    private void btnRedGivePoint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedGivePoint2ActionPerformed
        battle.setRedPoint(battle.getRedPoint() + 1);
        lblRedPoints.setText("" + battle.getRedPoint());
    }//GEN-LAST:event_btnRedGivePoint2ActionPerformed

    private void btnBlueGivePoint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlueGivePoint1ActionPerformed
        battle.setBluePoint(battle.getBluePoint() + 2);
        lblBluePoints.setText("" + battle.getBluePoint());
    }//GEN-LAST:event_btnBlueGivePoint1ActionPerformed

    private void btnBlueGivePoint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlueGivePoint2ActionPerformed
        battle.setBluePoint(battle.getBluePoint() + 1);
        lblBluePoints.setText("" + battle.getBluePoint());
    }//GEN-LAST:event_btnBlueGivePoint2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlueGivePoint;
    private javax.swing.JButton btnBlueGivePoint1;
    private javax.swing.JButton btnBlueGivePoint2;
    private javax.swing.JButton btnBlueGiveWarning;
    private javax.swing.JButton btnBlueRemoveWarning;
    private javax.swing.JButton btnBlueTakePoint;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCheckBlue;
    private javax.swing.JButton btnCheckRed;
    private javax.swing.JButton btnRedGivePoint;
    private javax.swing.JButton btnRedGivePoint1;
    private javax.swing.JButton btnRedGivePoint2;
    private javax.swing.JButton btnRedGiveWarning;
    private javax.swing.JButton btnRedRemoveWarning;
    private javax.swing.JButton btnRedTakePoint;
    private javax.swing.JToggleButton btnRemoveNew;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JButton btnTimerNewLap;
    private javax.swing.JButton btnTimerReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JScrollPane jspTournaments;
    private javax.swing.JScrollPane jspTournaments1;
    private javax.swing.JLabel lblBlueName;
    private javax.swing.JLabel lblBluePoints;
    private javax.swing.JLabel lblRedName;
    private javax.swing.JLabel lblRedPoints;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JList lstStopWatch;
    private javax.swing.JPanel pnlBlue;
    private javax.swing.JPanel pnlRed;
    private javax.swing.ButtonGroup rbgrFighter;
    private javax.swing.JTable tblBlueWarnings;
    private javax.swing.JTable tblRedWarnings;
    // End of variables declaration//GEN-END:variables
}
